export const CONTENT = {
  th: {
    lastUpdated: '25 กรกฎาคม 2569',
    version: '3.0',
    backHome: 'กลับหน้าหลัก',
    title: 'นโยบายความเป็นส่วนตัว',
    subtitle: 'Privacy Policy — PDPA Compliance',
    updatedLabel: 'อัปเดตล่าสุด',
    versionLabel: 'เวอร์ชัน',
    intro: 'ชุมนุมคอมพิวเตอร์ คณะวิทยาศาสตร์ มหาวิทยาลัยสงขลานครินทร์ ("SCC Shop", "เรา", "ของเรา") ให้ความสำคัญกับความเป็นส่วนตัวของข้อมูลของท่าน นโยบายความเป็นส่วนตัวฉบับนี้อธิบายวิธีการที่เราเก็บรวบรวม ใช้ เปิดเผย และคุ้มครองข้อมูลส่วนบุคคลของท่าน ตามพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 (PDPA)',
    promise: {
      title: 'คำมั่นสัญญาของเรา:',
      text: 'เราจะไม่ขายหรือเปิดเผยข้อมูลส่วนบุคคลของท่านให้กับบุคคลภายนอก เว้นแต่จะได้รับความยินยอมจากท่านหรือตามที่กฎหมายกำหนด ข้อมูลทั้งหมดถูกเข้ารหัสและจัดเก็บอย่างปลอดภัย',
    },
    s1: {
      title: '1. ข้อมูลที่เราเก็บรวบรวม',
      desc: 'เราเก็บรวบรวมข้อมูลส่วนบุคคลของท่านเฉพาะเท่าที่จำเป็นสำหรับการให้บริการ:',
      directTitle: 'ข้อมูลที่ท่านให้โดยตรง:',
      direct: [
        { primary: 'ชื่อ-นามสกุล', secondary: 'สำหรับการจัดส่งสินค้า สกรีนบนสินค้า และการติดต่อ' },
        { primary: 'อีเมล', secondary: 'สำหรับการยืนยันตัวตน (OAuth) และการแจ้งสถานะคำสั่งซื้อ' },
        { primary: 'หมายเลขโทรศัพท์', secondary: 'สำหรับการติดต่อกรณีมีปัญหาการจัดส่ง' },
        { primary: 'ที่อยู่จัดส่ง', secondary: 'สำหรับการจัดส่งสินค้า (รองรับบันทึกหลายที่อยู่)' },
        { primary: 'Instagram', secondary: 'สำหรับการติดต่อทางช่องทางเสริม' },
        { primary: 'หลักฐานการชำระเงิน (สลิป)', secondary: 'สำหรับการยืนยันการชำระเงินผ่านระบบ SlipOK' },
        { primary: 'ข้อมูลบัญชีธนาคาร (กรณีขอคืนเงิน)', secondary: 'สำหรับดำเนินการคืนเงิน เก็บเฉพาะกรณีท่านขอ Refund' },
        { primary: 'ข้อความในแชทสนับสนุน', secondary: 'สำหรับการให้บริการช่วยเหลือจากทีมงาน' },
        { primary: 'ข้อความที่ส่งถึง AI Chatbot', secondary: 'สำหรับการตอบคำถามอัตโนมัติ ส่งไปประมวลผลที่ Google Gemini' },
      ],
      autoTitle: 'ข้อมูลที่เก็บรวบรวมโดยอัตโนมัติ:',
      auto: [
        { primary: 'ข้อมูลการเข้าสู่ระบบ (OAuth 2.0)', secondary: 'ผ่าน Google, Microsoft, Facebook, Apple หรือ LINE Account' },
        { primary: 'IP Address', secondary: 'สำหรับการรักษาความปลอดภัย (เก็บแบบเข้ารหัส/ปกปิดบางส่วน)' },
        { primary: 'User Agent', secondary: 'สำหรับการตรวจจับภัยคุกคามและอุปกรณ์ผิดปกติ' },
        { primary: 'คุกกี้', secondary: 'สำหรับการจดจำ Session, ตะกร้าสินค้า และการตั้งค่า' },
        { primary: 'บันทึกกิจกรรม (Activity Logs)', secondary: 'เข้าสู่ระบบ, ออกจากระบบ, สั่งซื้อ — สำหรับการตรวจสอบความปลอดภัย' },
        { primary: 'บันทึกความปลอดภัย (Security Audit Logs)', secondary: 'ประเภทเหตุการณ์, ระดับความรุนแรง, คะแนนภัยคุกคาม' },
      ],
      orderTitle: 'ข้อมูลคำสั่งซื้อ:',
      order: [
        { primary: 'รายการสินค้าในตะกร้า', secondary: 'ชื่อสินค้า, ไซซ์, จำนวน, ออปชั่นสกรีนชื่อ/เบอร์, แขนสั้น/ยาว' },
        { primary: 'ข้อมูลการชำระเงิน', secondary: 'ยอดรวม, วิธีชำระ, สถานะการยืนยัน, รหัสอ้างอิงธุรกรรม' },
        { primary: 'ข้อมูลการจัดส่ง', secondary: 'วิธีจัดส่ง, ค่าจัดส่ง, เลขพัสดุ, สถานะการจัดส่ง' },
        { primary: 'ข้อมูลการคืนเงิน (ถ้ามี)', secondary: 'เหตุผล, จำนวนเงิน, สถานะ, ข้อมูลบัญชีคืนเงิน' },
      ],
    },
    s2: {
      title: '2. วัตถุประสงค์ในการใช้ข้อมูล',
      items: [
        'ดำเนินการตามคำสั่งซื้อ จัดเตรียม และจัดส่งสินค้า',
        'ยืนยันการชำระเงินและตรวจสอบสลิปอัตโนมัติ (ผ่าน SlipOK)',
        'แจ้งสถานะคำสั่งซื้อ สถานะการจัดส่ง และเลขพัสดุทางอีเมล',
        'ติดต่อกรณีมีปัญหาเกี่ยวกับคำสั่งซื้อหรือการจัดส่ง',
        'ให้บริการ AI Chatbot ตอบคำถามและช่วยค้นหาข้อมูลสินค้า/ออเดอร์',
        'ให้บริการแชทสนับสนุนจากทีมงาน (Support Chat)',
        'ดำเนินการคืนเงินเมื่อท่านร้องขอ (Refund System)',
        'ติดตามสถานะพัสดุแบบ Real-time (ผ่าน Track123)',
        'บันทึกข้อมูลคำสั่งซื้อลง Google Sheets สำหรับการจัดการภายใน',
        'ป้องกันการทุจริต ตรวจจับภัยคุกคาม และรักษาความปลอดภัยของระบบ',
        'ปฏิบัติตามกฎหมายที่เกี่ยวข้อง รวมถึง PDPA',
      ],
    },
    s3: {
      title: '3. การยืนยันตัวตน (Authentication)',
      desc: 'เราใช้ระบบ OAuth 2.0 ผ่าน NextAuth.js สำหรับการยืนยันตัวตน โดยรองรับผู้ให้บริการดังนี้:',
      providers: [
        { provider: 'Google', data: 'ชื่อ, อีเมล, รูปโปรไฟล์', note: 'ผู้ให้บริการหลัก' },
        { provider: 'Microsoft (Azure AD)', data: 'ชื่อ, อีเมลองค์กร, รูปโปรไฟล์', note: 'สำหรับบัญชี Microsoft/Outlook' },
        { provider: 'Facebook', data: 'ชื่อ, อีเมล, รูปโปรไฟล์', note: 'เปิดใช้งานตามเงื่อนไข' },
        { provider: 'Apple', data: 'ชื่อ, อีเมล (หรือ Private Relay Email)', note: 'รองรับ Hide My Email' },
        { provider: 'LINE', data: 'ชื่อ, อีเมล (ถ้ามี), รูปโปรไฟล์', note: 'สำหรับผู้ใช้ LINE' },
      ],
      note: 'เราใช้ JWT (JSON Web Token) สำหรับการจัดการ Session โดยมีอายุสูงสุด 30 วัน ข้อมูลอีเมลจะถูกแปลงเป็นรหัส SHA-256 เพื่อใช้เป็นคีย์ในการจัดเก็บข้อมูล เพิ่มความปลอดภัยในการอ้างอิง',
    },
    s4: {
      title: '4. AI Chatbot และ Support Chat',
      aiTitle: 'AI Chatbot (SCC Bot)',
      aiItems: [
        'ใช้ Google Gemini AI สำหรับการประมวลผลคำถาม',
        'ข้อความที่ท่านส่งจะถูกส่งไปยัง Google Gemini API เพื่อสร้างคำตอบ',
        'หากท่านล็อกอินแล้ว ระบบอาจค้นหาข้อมูลออเดอร์ของท่านเพื่อตอบคำถามเกี่ยวกับสถานะสั่งซื้อ',
        'ประวัติการสนทนาเก็บไว้ในเบราว์เซอร์ของท่านเท่านั้น (Session-based) ไม่ได้เก็บในเซิร์ฟเวอร์',
        'ระบบจะไม่เปิดเผยข้อมูลส่วนตัวของลูกค้าคนอื่นผ่าน AI Chatbot',
      ],
      supportTitle: 'Support Chat (แชทกับทีมงาน)',
      supportItems: [
        'ข้อความแชทถูกเก็บในฐานข้อมูลเพื่อให้ทีมงานตอบกลับได้',
        'ข้อมูลที่เก็บ: ข้อความ, ชื่อ, อีเมล, วันเวลา, การอ่านข้อความ',
        'รองรับการอัปโหลดรูปภาพประกอบการสนทนา',
        'ท่านสามารถให้คะแนนความพึงพอใจหลังจบการสนทนาได้',
        'ข้อมูลแชทจะถูกเก็บรักษาตามระยะเวลาที่กำหนดในหมวดการเก็บรักษาข้อมูล',
      ],
    },
    s5: {
      title: '5. ระยะเวลาในการเก็บรักษาข้อมูล',
      items: [
        { type: 'ข้อมูลคำสั่งซื้อ', duration: '2 ปี นับจากวันที่สั่งซื้อ', note: 'ตามข้อกำหนดทางบัญชี' },
        { type: 'หลักฐานการชำระเงิน', duration: '2 ปี นับจากวันที่ชำระเงิน', note: 'เพื่อการตรวจสอบ' },
        { type: 'ข้อมูลโปรไฟล์ผู้ใช้', duration: 'จนกว่าจะขอลบ', note: 'สามารถขอลบได้ทุกเมื่อ' },
        { type: 'ข้อความ Support Chat', duration: '1 ปี', note: 'หลังจากปิดการสนทนา' },
        { type: 'ข้อความ AI Chatbot', duration: 'ไม่เก็บในเซิร์ฟเวอร์', note: 'เก็บในเบราว์เซอร์เท่านั้น' },
        { type: 'ข้อมูลการคืนเงิน', duration: '2 ปี นับจากวันดำเนินการ', note: 'ตามข้อกำหนดทางบัญชี' },
        { type: 'บันทึกกิจกรรมผู้ใช้', duration: '2 ปี', note: 'สำหรับการตรวจสอบและ audit ตามกฏหมาย' },
        { type: 'บันทึกความปลอดภัย', duration: '2 ปี', note: 'สำหรับการตรวจจับภัยคุกคามและสอบสวน' },
        { type: 'Audit trail (before/after)', duration: '2 ปี', note: 'บันทึกการแก้ไขออเดอร์ สิทธิ์ การตั้งค่า' },
        { type: 'คุกกี้', duration: '1 ปี', note: 'หรือจนกว่าจะลบออก' },
        { type: 'บันทึกอีเมลที่ส่ง', duration: '1 ปี', note: 'เพื่อการตรวจสอบ' },
      ],
      autoClean: {
        title: 'ระบบทำความสะอาดอัตโนมัติ:',
        text: 'เรามีระบบ Cron Job ที่ทำงานเป็นระยะ เพื่อลบข้อมูลที่หมดอายุตาม PDPA, ยกเลิกออเดอร์ที่ไม่ชำระเงินภายในกำหนด และอัปเดตสถานะพัสดุอัตโนมัติ',
      },
    },
    s6: {
      title: '6. สิทธิ์ของเจ้าของข้อมูล (PDPA Rights)',
      desc: 'ตาม พ.ร.บ. คุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 ท่านมีสิทธิ์ดังต่อไปนี้:',
      rights: [
        { title: 'สิทธิ์ในการเข้าถึง', desc: 'ท่านสามารถขอดูข้อมูลส่วนบุคคลที่เราเก็บรักษาไว้เกี่ยวกับท่าน ผ่านระบบ Data Request ในเว็บไซต์ หรือส่งอีเมลมาที่ทีมงาน', color: '#2563eb' },
        { title: 'สิทธิ์ในการขอรับข้อมูล (Data Portability)', desc: 'ท่านสามารถขอรับสำเนาข้อมูลส่วนบุคคลของท่านในรูปแบบ JSON ที่อ่านได้ ผ่านระบบ Data Export', color: '#0ea5e9' },
        { title: 'สิทธิ์ในการแก้ไขข้อมูล', desc: 'ท่านสามารถแก้ไขข้อมูลโปรไฟล์ (ชื่อ, เบอร์โทร, ที่อยู่, Instagram) ได้ด้วยตนเองผ่านหน้าโปรไฟล์', color: '#f59e0b' },
        { title: 'สิทธิ์ในการลบข้อมูล', desc: 'ท่านสามารถขอให้ลบข้อมูลส่วนบุคคลของท่านได้ ยกเว้นข้อมูลคำสั่งซื้อที่ต้องเก็บตามข้อกำหนดทางบัญชี', color: '#ef4444' },
        { title: 'สิทธิ์ในการระงับการใช้', desc: 'ท่านสามารถขอให้ระงับการใช้ข้อมูลส่วนบุคคลของท่านชั่วคราวได้', color: '#1e40af' },
        { title: 'สิทธิ์ในการคัดค้าน', desc: 'ท่านสามารถคัดค้านการประมวลผลข้อมูลส่วนบุคคลของท่าน เช่น การส่งอีเมลประชาสัมพันธ์', color: '#ec4899' },
      ],
      howToTitle: 'วิธีการใช้สิทธิ์:',
      howTo: '1. ผ่านระบบ Data Request ในเว็บไซต์ (เมนู Privacy > Data Request)\n2. ส่งคำขอมาที่อีเมล',
      howToSuffix: 'พร้อมระบุชื่อ-อีเมลที่ใช้สั่งซื้อ และสิทธิ์ที่ต้องการใช้',
      howToDeadline: 'เราจะดำเนินการภายใน 30 วัน นับจากวันที่ได้รับคำขอ',
    },
    s7: {
      title: '7. มาตรการรักษาความปลอดภัย',
      desc: 'เราใช้มาตรการรักษาความปลอดภัยหลายระดับตามมาตรฐานสากล:',
      items: [
        'การเข้ารหัส HTTPS/TLS', 'Content Security Policy (CSP)', 'เข้ารหัสข้อมูล AES-256-GCM',
        'แฮชอีเมลด้วย SHA-256', 'OAuth 2.0 + JWT Session', 'HMAC-SHA256 Request Signing',
        'Rate Limiting หลายระดับ', 'ป้องกัน SQL/XSS Injection', 'Cloudflare Turnstile (CAPTCHA)',
        'Threat Detection อัตโนมัติ', 'API Key Rotation อัตโนมัติ', 'Security Audit Logging',
        'Brute Force Protection', 'Role-Based Access (14 Permissions)', 'Encrypted Image Proxy URLs', 'Sensitive Field Stripping',
      ],
    },
    s8: {
      title: '8. นโยบายคุกกี้',
      desc: 'เราใช้คุกกี้เพื่อปรับปรุงประสบการณ์การใช้งานของท่าน โดยแบ่งออกเป็น 4 ประเภท:',
      types: [
        { type: 'คุกกี้ที่จำเป็น (Essential)', required: true, desc: 'สำหรับการทำงานพื้นฐาน เช่น NextAuth Session, CSRF Protection, Cloudflare Turnstile' },
        { type: 'คุกกี้ฟังก์ชัน (Functional)', required: false, desc: 'สำหรับจดจำตะกร้าสินค้า (Zustand), ข้อมูลโปรไฟล์, ธีมสว่าง/มืด, Cookie Consent' },
        { type: 'คุกกี้วิเคราะห์ (Analytics)', required: false, desc: 'สำหรับเข้าใจพฤติกรรมการใช้งานเพื่อปรับปรุงบริการ' },
        { type: 'คุกกี้การตลาด (Marketing)', required: false, desc: 'สำหรับแสดงโฆษณาที่ตรงกับความสนใจของท่าน (ปัจจุบันไม่ได้ใช้)' },
      ],
      required: 'จำเป็น',
      manage: 'ท่านสามารถจัดการการตั้งค่าคุกกี้ได้ผ่าน Cookie Banner ที่ด้านล่างของหน้าเว็บ หรือลบคุกกี้ทั้งหมดผ่านการตั้งค่าเบราว์เซอร์',
    },
    s9: {
      title: '9. การเปิดเผยข้อมูลต่อบุคคลภายนอก',
      desc: 'เราอาจเปิดเผยข้อมูลส่วนบุคคลของท่านให้กับบุคคลภายนอกในกรณีต่อไปนี้เท่านั้น:',
      dataSent: 'ข้อมูลที่ส่ง',
      parties: [
        { party: 'Google (OAuth + Gemini AI)', purpose: 'ยืนยันตัวตน, ประมวลผลคำถาม AI Chatbot', data: 'อีเมล, ชื่อ, ข้อความ Chatbot' },
        { party: 'Microsoft Azure AD', purpose: 'ยืนยันตัวตนด้วยบัญชี Microsoft', data: 'อีเมล, ชื่อ' },
        { party: 'Facebook', purpose: 'ยืนยันตัวตนด้วยบัญชี Facebook', data: 'อีเมล, ชื่อ' },
        { party: 'Apple', purpose: 'ยืนยันตัวตนด้วยบัญชี Apple (รองรับ Hide My Email)', data: 'อีเมล, ชื่อ' },
        { party: 'LINE', purpose: 'ยืนยันตัวตนด้วยบัญชี LINE', data: 'อีเมล (ถ้ามี), ชื่อ' },
        { party: 'Supabase', purpose: 'ฐานข้อมูลหลัก, จัดเก็บรูปภาพ, Real-time Updates', data: 'ข้อมูลคำสั่งซื้อ, โปรไฟล์, แชท' },
        { party: 'Cloudflare (Turnstile)', purpose: 'ป้องกัน Bot, CDN, ความปลอดภัย', data: 'IP Address, Turnstile Token' },
        { party: 'Resend', purpose: 'ส่งอีเมลแจ้งเตือนสถานะคำสั่งซื้อ', data: 'อีเมลผู้รับ, เนื้อหาอีเมล' },
        { party: 'SlipOK', purpose: 'ตรวจสอบสลิปการชำระเงินอัตโนมัติ', data: 'รูปสลิป, รหัสอ้างอิงธุรกรรม' },
        { party: 'Google Sheets', purpose: 'Sync ข้อมูลคำสั่งซื้อสำหรับทีมงาน', data: 'ข้อมูลคำสั่งซื้อ (ชื่อ, รายการ, ยอด)' },
        { party: 'Track123', purpose: 'ติดตามสถานะพัสดุแบบ Real-time', data: 'เลขพัสดุ, รหัสขนส่ง' },
        { party: 'Filebase (IPFS/S3)', purpose: 'จัดเก็บรูปภาพสินค้าและไฟล์', data: 'รูปภาพ, ไฟล์ config' },
      ],
      noteTitle: 'หมายเหตุ:',
      noteText: 'เราจะไม่ขายหรือให้เช่าข้อมูลส่วนบุคคลของท่านแก่บุคคลภายนอกเด็ดขาด บริการภายนอกทั้งหมดถูกใช้เพื่อการให้บริการที่จำเป็นเท่านั้น',
    },
    s10: {
      title: '10. การชำระเงินและการจัดส่ง',
      paymentTitle: 'การชำระเงิน',
      paymentItems: [
        'รองรับ PromptPay QR Code — สร้าง QR Code ภายในเว็บไซต์ ไม่ผ่านบริการภายนอก',
        'รองรับโอนเงินผ่านธนาคาร',
        'สลิปการโอนเงินจะถูกอัปโหลดและตรวจสอบอัตโนมัติผ่าน SlipOK',
        'ข้อมูลสลิปเข้าถึงได้เฉพาะผู้ดูแลระบบเท่านั้น',
        'ระบบ Refund — ท่านสามารถขอคืนเงินกรณีสินค้ามีปัญหา พร้อมระบุบัญชีรับเงินคืน',
      ],
      shippingTitle: 'การจัดส่ง',
      shippingItems: [
        'รองรับหลายรูปแบบจัดส่ง (รับหน้าร้าน, ส่งไปรษณีย์ ฯลฯ)',
        'ที่อยู่จัดส่งเก็บเข้ารหัสอย่างปลอดภัย เข้าถึงได้เฉพาะทีมจัดส่ง',
        'เลขพัสดุติดตามผ่าน Track123 — ส่งเฉพาะเลขพัสดุและรหัสขนส่ง',
        'รองรับบันทึกที่อยู่จัดส่งหลายแห่ง (Address Book)',
        'การรับหน้าร้านใช้ QR Code ยืนยันตัวตน',
      ],
    },
    s11: {
      title: '11. ช่องทางติดต่อ (Data Protection Officer)',
      desc: 'หากท่านมีคำถามเกี่ยวกับนโยบายความเป็นส่วนตัว หรือต้องการใช้สิทธิ์ของเจ้าของข้อมูล สามารถติดต่อเราได้ที่:',
      orgName: 'ชุมนุมคอมพิวเตอร์ คณะวิทยาศาสตร์',
      orgAddr: 'มหาวิทยาลัยสงขลานครินทร์ วิทยาเขตหาดใหญ่',
      email: 'อีเมล',
      website: 'เว็บไซต์',
      facebook: 'ชุมนุมคอมพิวเตอร์ คณะวิทยาศาสตร์ ม.อ.',
      chatLabel: 'ผ่านปุ่มแชทในเว็บไซต์',
    },
    s12: {
      title: '12. การเปลี่ยนแปลงนโยบาย',
      desc: 'เราอาจปรับปรุงนโยบายความเป็นส่วนตัวนี้เป็นครั้งคราว หากมีการเปลี่ยนแปลงที่สำคัญ เราจะแจ้งให้ท่านทราบผ่านทางอีเมลหรือประกาศบนเว็บไซต์ การใช้งานเว็บไซต์ต่อหลังจากมีการเปลี่ยนแปลงนโยบาย ถือว่าท่านยอมรับนโยบายฉบับใหม่',
      v3: { date: '7 กุมภาพันธ์ 2569', desc: 'เพิ่มข้อมูล AI Chatbot, Support Chat, Refund System, 5 OAuth Providers, มาตรการความปลอดภัยเพิ่มเติม' },
      v2: { date: '20 มกราคม 2569', desc: 'ปรับปรุงนโยบายให้สอดคล้องกับ PDPA, เพิ่มสิทธิ์เจ้าของข้อมูล' },
      v1: { date: 'เปิดตัวครั้งแรก', desc: 'นโยบายความเป็นส่วนตัวฉบับแรก' },
    },
    copyright: '© 2569 ชุมนุมคอมพิวเตอร์ คณะวิทยาศาสตร์ มหาวิทยาลัยสงขลานครินทร์ สงวนลิขสิทธิ์',
  },
  en: {
    lastUpdated: 'July 25, 2026',
    version: '3.0',
    backHome: 'Back to Home',
    title: 'Privacy Policy',
    subtitle: 'Privacy Policy — PDPA Compliance',
    updatedLabel: 'Last Updated',
    versionLabel: 'Version',
    intro: 'The Science Computer Club, Faculty of Science, Prince of Songkla University ("SCC Shop", "we", "our") values the privacy of your personal data. This Privacy Policy explains how we collect, use, disclose, and protect your personal data in accordance with the Personal Data Protection Act B.E. 2562 (PDPA).',
    promise: {
      title: 'Our Commitment:',
      text: 'We will not sell or disclose your personal data to third parties without your consent or as required by law. All data is encrypted and stored securely.',
    },
    s1: {
      title: '1. Data We Collect',
      desc: 'We collect your personal data only as necessary to provide our services:',
      directTitle: 'Data you provide directly:',
      direct: [
        { primary: 'Full Name', secondary: 'For shipping, product printing, and communication' },
        { primary: 'Email', secondary: 'For identity verification (OAuth) and order status notifications' },
        { primary: 'Phone Number', secondary: 'For contacting you in case of shipping issues' },
        { primary: 'Shipping Address', secondary: 'For product delivery (supports saving multiple addresses)' },
        { primary: 'Instagram', secondary: 'For alternative contact channel' },
        { primary: 'Payment Proof (Slip)', secondary: 'For payment verification via SlipOK system' },
        { primary: 'Bank Account Info (for refunds)', secondary: 'For processing refunds, stored only when you request a refund' },
        { primary: 'Support Chat Messages', secondary: 'For customer support services from our team' },
        { primary: 'AI Chatbot Messages', secondary: 'For automated Q&A, processed by Google Gemini' },
      ],
      autoTitle: 'Data collected automatically:',
      auto: [
        { primary: 'Login Data (OAuth 2.0)', secondary: 'Via Google, Microsoft, Facebook, Apple, or LINE Account' },
        { primary: 'IP Address', secondary: 'For security purposes (stored encrypted/partially masked)' },
        { primary: 'User Agent', secondary: 'For threat detection and abnormal device monitoring' },
        { primary: 'Cookies', secondary: 'For session management, shopping cart, and preferences' },
        { primary: 'Activity Logs', secondary: 'Login, logout, orders — for security auditing' },
        { primary: 'Security Audit Logs', secondary: 'Event type, severity level, threat score' },
      ],
      orderTitle: 'Order Data:',
      order: [
        { primary: 'Cart Items', secondary: 'Product name, size, quantity, custom name/number options, sleeve type' },
        { primary: 'Payment Data', secondary: 'Total amount, payment method, verification status, transaction reference' },
        { primary: 'Shipping Data', secondary: 'Shipping method, shipping fee, tracking number, delivery status' },
        { primary: 'Refund Data (if applicable)', secondary: 'Reason, amount, status, refund account info' },
      ],
    },
    s2: {
      title: '2. Purpose of Data Usage',
      items: [
        'Process orders, prepare, and ship products',
        'Verify payments and automatically check transfer slips (via SlipOK)',
        'Notify order status, shipping status, and tracking numbers via email',
        'Contact you regarding order or shipping issues',
        'Provide AI Chatbot for Q&A and product/order search',
        'Provide team support chat (Support Chat)',
        'Process refunds upon your request (Refund System)',
        'Track parcels in real-time (via Track123)',
        'Sync order data to Google Sheets for internal management',
        'Prevent fraud, detect threats, and maintain system security',
        'Comply with applicable laws, including PDPA',
      ],
    },
    s3: {
      title: '3. Authentication',
      desc: 'We use OAuth 2.0 via NextAuth.js for identity verification, supporting the following providers:',
      providers: [
        { provider: 'Google', data: 'Name, Email, Profile Picture', note: 'Primary Provider' },
        { provider: 'Microsoft (Azure AD)', data: 'Name, Organizational Email, Profile Picture', note: 'For Microsoft/Outlook accounts' },
        { provider: 'Facebook', data: 'Name, Email, Profile Picture', note: 'Conditionally enabled' },
        { provider: 'Apple', data: 'Name, Email (or Private Relay Email)', note: 'Supports Hide My Email' },
        { provider: 'LINE', data: 'Name, Email (if available), Profile Picture', note: 'For LINE users' },
      ],
      note: 'We use JWT (JSON Web Token) for session management with a maximum lifetime of 30 days. Email addresses are hashed using SHA-256 to serve as storage keys, enhancing security in data referencing.',
    },
    s4: {
      title: '4. AI Chatbot & Support Chat',
      aiTitle: 'AI Chatbot (SCC Bot)',
      aiItems: [
        'Uses Google Gemini AI for processing questions',
        'Messages you send are forwarded to Google Gemini API to generate responses',
        'If you are logged in, the system may search your order data to answer order status questions',
        'Conversation history is stored in your browser only (session-based), not on servers',
        'The system will not disclose other customers\' personal data through the AI Chatbot',
      ],
      supportTitle: 'Support Chat (Chat with Team)',
      supportItems: [
        'Chat messages are stored in the database so the team can respond',
        'Data stored: messages, name, email, timestamps, read status',
        'Supports image uploads for conversation context',
        'You can rate your satisfaction after a conversation ends',
        'Chat data is retained according to the Data Retention section',
      ],
    },
    s5: {
      title: '5. Data Retention Period',
      items: [
        { type: 'Order Data', duration: '2 years from order date', note: 'Per accounting requirements' },
        { type: 'Payment Proof', duration: '2 years from payment date', note: 'For auditing' },
        { type: 'User Profile Data', duration: 'Until deletion request', note: 'Can request deletion anytime' },
        { type: 'Support Chat Messages', duration: '1 year', note: 'After conversation closes' },
        { type: 'AI Chatbot Messages', duration: 'Not stored on server', note: 'Browser-only storage' },
        { type: 'Refund Data', duration: '2 years from processing', note: 'Per accounting requirements' },
        { type: 'User Activity Logs', duration: '2 years', note: 'For auditing and legal review' },
        { type: 'Security Logs', duration: '2 years', note: 'For threat detection and investigation' },
        { type: 'Audit trail (before/after)', duration: '2 years', note: 'Order, permission, and config changes' },
        { type: 'Cookies', duration: '1 year', note: 'Or until deleted' },
        { type: 'Email Send Logs', duration: '1 year', note: 'For auditing' },
      ],
      autoClean: {
        title: 'Automatic Cleanup System:',
        text: 'We have a Cron Job system that runs periodically to delete expired data per PDPA, cancel unpaid orders past the deadline, and automatically update parcel statuses.',
      },
    },
    s6: {
      title: '6. Data Subject Rights (PDPA Rights)',
      desc: 'Under the Personal Data Protection Act B.E. 2562, you have the following rights:',
      rights: [
        { title: 'Right of Access', desc: 'You can request to view your personal data that we maintain through the Data Request system on our website or by emailing our team.', color: '#2563eb' },
        { title: 'Right to Data Portability', desc: 'You can request a copy of your personal data in a readable JSON format through the Data Export system.', color: '#0ea5e9' },
        { title: 'Right to Rectification', desc: 'You can edit your profile data (name, phone, address, Instagram) yourself through the profile page.', color: '#f59e0b' },
        { title: 'Right to Erasure', desc: 'You can request deletion of your personal data, except order data that must be retained per accounting requirements.', color: '#ef4444' },
        { title: 'Right to Restrict Processing', desc: 'You can request temporary suspension of your personal data processing.', color: '#1e40af' },
        { title: 'Right to Object', desc: 'You can object to the processing of your personal data, such as promotional emails.', color: '#ec4899' },
      ],
      howToTitle: 'How to Exercise Your Rights:',
      howTo: '1. Through the Data Request system on the website (Menu: Privacy > Data Request)\n2. Send a request to email',
      howToSuffix: 'with your name, email used for orders, and the right you wish to exercise',
      howToDeadline: 'We will process your request within 30 days of receipt.',
    },
    s7: {
      title: '7. Security Measures',
      desc: 'We implement multi-layered security measures following international standards:',
      items: [
        'HTTPS/TLS Encryption', 'Content Security Policy (CSP)', 'AES-256-GCM Data Encryption',
        'SHA-256 Email Hashing', 'OAuth 2.0 + JWT Session', 'HMAC-SHA256 Request Signing',
        'Multi-level Rate Limiting', 'SQL/XSS Injection Prevention', 'Cloudflare Turnstile (CAPTCHA)',
        'Automatic Threat Detection', 'Automatic API Key Rotation', 'Security Audit Logging',
        'Brute Force Protection', 'Role-Based Access (14 Permissions)', 'Encrypted Image Proxy URLs', 'Sensitive Field Stripping',
      ],
    },
    s8: {
      title: '8. Cookie Policy',
      desc: 'We use cookies to improve your experience, categorized into 4 types:',
      types: [
        { type: 'Essential Cookies', required: true, desc: 'For basic functionality such as NextAuth Session, CSRF Protection, Cloudflare Turnstile' },
        { type: 'Functional Cookies', required: false, desc: 'For remembering cart (Zustand), profile data, light/dark theme, Cookie Consent' },
        { type: 'Analytics Cookies', required: false, desc: 'For understanding usage behavior to improve services' },
        { type: 'Marketing Cookies', required: false, desc: 'For displaying relevant advertisements (currently not used)' },
      ],
      required: 'Required',
      manage: 'You can manage cookie settings through the Cookie Banner at the bottom of the page or delete all cookies through your browser settings.',
    },
    s9: {
      title: '9. Third-Party Data Disclosure',
      desc: 'We may disclose your personal data to third parties only in the following cases:',
      dataSent: 'Data Sent',
      parties: [
        { party: 'Google (OAuth + Gemini AI)', purpose: 'Authentication, AI Chatbot processing', data: 'Email, Name, Chatbot messages' },
        { party: 'Microsoft Azure AD', purpose: 'Authentication with Microsoft account', data: 'Email, Name' },
        { party: 'Facebook', purpose: 'Authentication with Facebook account', data: 'Email, Name' },
        { party: 'Apple', purpose: 'Authentication with Apple account (Hide My Email supported)', data: 'Email, Name' },
        { party: 'LINE', purpose: 'Authentication with LINE account', data: 'Email (if available), Name' },
        { party: 'Supabase', purpose: 'Main database, Image storage, Real-time Updates', data: 'Order data, Profile, Chat' },
        { party: 'Cloudflare (Turnstile)', purpose: 'Bot prevention, CDN, Security', data: 'IP Address, Turnstile Token' },
        { party: 'Resend', purpose: 'Send order status notification emails', data: 'Recipient email, Email content' },
        { party: 'SlipOK', purpose: 'Automatic payment slip verification', data: 'Slip image, Transaction reference' },
        { party: 'Google Sheets', purpose: 'Sync order data for team management', data: 'Order data (name, items, total)' },
        { party: 'Track123', purpose: 'Real-time parcel tracking', data: 'Tracking number, Courier code' },
        { party: 'Filebase (IPFS/S3)', purpose: 'Product image and file storage', data: 'Images, Config files' },
      ],
      noteTitle: 'Note:',
      noteText: 'We will never sell or rent your personal data to third parties. All external services are used only to provide necessary services.',
    },
    s10: {
      title: '10. Payment & Shipping',
      paymentTitle: 'Payment',
      paymentItems: [
        'Supports PromptPay QR Code — QR generated within the website, no external service',
        'Supports bank transfer',
        'Transfer slips are uploaded and automatically verified via SlipOK',
        'Slip data is accessible only to administrators',
        'Refund System — You can request a refund for defective products with your refund account details',
      ],
      shippingTitle: 'Shipping',
      shippingItems: [
        'Supports multiple shipping methods (pickup, postal service, etc.)',
        'Shipping addresses are securely encrypted, accessible only to the shipping team',
        'Parcel tracking via Track123 — only tracking number and courier code are sent',
        'Supports saving multiple shipping addresses (Address Book)',
        'Pickup uses QR Code for identity verification',
      ],
    },
    s11: {
      title: '11. Contact (Data Protection Officer)',
      desc: 'If you have questions about our Privacy Policy or wish to exercise your data subject rights, please contact us:',
      orgName: 'Science Computer Club, Faculty of Science',
      orgAddr: 'Prince of Songkla University, Hat Yai Campus',
      email: 'Email',
      website: 'Website',
      facebook: 'Science Computer Club, Faculty of Science, PSU',
      chatLabel: 'Via chat button on the website',
    },
    s12: {
      title: '12. Policy Changes',
      desc: 'We may update this Privacy Policy from time to time. If there are significant changes, we will notify you via email or announcement on the website. Continued use of the website after policy changes constitutes acceptance of the new policy.',
      v3: { date: 'February 7, 2026', desc: 'Added AI Chatbot, Support Chat, Refund System, 5 OAuth Providers, additional security measures' },
      v2: { date: 'January 20, 2026', desc: 'Updated policy for PDPA compliance, added data subject rights' },
      v1: { date: 'Initial Launch', desc: 'First version of the Privacy Policy' },
    },
    copyright: '© 2026 Science Computer Club, Faculty of Science, Prince of Songkla University. All rights reserved.',
  },
};

export type PrivacyLang = keyof typeof CONTENT;
